spring:
  datasource:
    # Render가 주는 postgres:// 주소를 Spring이 인식하는 jdbc:postgresql:// 로 변환해야 할 수도 있습니다.
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update